branches: main
repositoryUrl: https://github.com/ae-lexs/aws_nat_gateway
plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/npm':
        npmPublish: false
    - '@semantic-release/changelog'
    - '@semantic-release/git'