version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.15.5
  terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light

jobs:
  generate_release:
    executor: node
    steps:
      - checkout
      - run:
          name: 'Generate Release'
          command: |
            sudo npm i -g @semantic-release/changelog @semantic-release/git semantic-release
            semantic-release          

  terraform_validate:
    executor: terraform
    steps:
      - checkout
      - run:
          name: 'Run the Terraform validator'
          command: terraform validate

workflows:
  version: 2

  development:
    jobs:
      - terraform_validate:
          filters:
            branches:
              only: main
      - generate_release:
          requires:
            - terraform_validate
          filters:
            branches:
              only: main