version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.15.5
  terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light

commands:
  initialize_terraform:
    description: Initialize the terraform project
    steps:
      - run:
          name: Terraform Version
          command: terraform version
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Get Local Modules
          command: terraform get

jobs:
  generate_release:
    executor: node
    steps:
      - checkout
      - run:
          name: Generate Release
          command: |
            sudo npm i -g @semantic-release/changelog @semantic-release/git semantic-release
            semantic-release          

  terraform_validate:
    executor: terraform
    steps:
      - checkout
      - initialize_terraform
      - run:
          name: Terraform Validate
          command: terraform validate

workflows:
  version: 2

  development:
    jobs:
      - terraform_validate:
          filters:
            branches:
              only: main
      - generate_release:
          requires:
            - terraform_validate
          filters:
            branches:
              only: main